### ISSUE TITLE
New art

### ISSUE THREAD

**Issue by will-janz** [will-janz/factorio-simple-saplings#4]
The original creator said it best: "I'm a programmer, not an artist."

Get new art.

Art requirements:
- Sapling item
- Planted sapling
- Research sprite with both combined

**Comment by SpaceReptile** [comment]
Tried a bit of work on all of the above. Hope it's the kind of thing you're looking for.
[graphics.zip](https://github.com/will-janz/factorio-simple-saplings/files/784540/graphics.zip)

**Comment by will-janz** [comment]
I think these look good. Thank you! Once these are in, how would you like to be credited?

**Comment by SpaceReptile** [comment]
Don't mind too much on that. A tag anywhere would be fine.

**Comment by will-janz** [comment]
New art added, publishing it now. Thanks!
