### ISSUE TITLE
Attempt to mutate global

### ISSUE THREAD

**Issue by Nexela** [will-janz/factorio-simple-saplings#5]
Just a friendly heads up that this will error.

Not allowed to mutate global in on_load

**Comment by will-janz** [comment]
If I need to change, say, `global.grow_interval` in the future (which I do, that's way too low for production), how should I go about that without needing to reinstall the mod?

**Comment by Nexela** [comment]
You have 2 options. First one is on_configuration_changed. This requires a change in version number to take effect (or adding/removed/updating any other mod causes this to trigger).  The second option is to add a remote interface to change the variable. this would allow you to do something like /c remote.call("sappling-growth", "grow_interval", 60)
